version: 2.1
orbs:
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.5.0

jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          args: tox
          pkg-manager: pip
          pypi-cache: false
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: tox
  test_pypi_publish:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          command: |  # create whl, install twine and publish to Test PyPI
            python setup.py sdist bdist_wheel
            sudo pip install pipenv
            pipenv install twine
            pipenv run twine upload --repository testpypi dist/*
  pypi_publish:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          command: |  # create whl, install twine and publish to PyPI
            python setup.py sdist bdist_wheel
            sudo pip install pipenv
            pipenv install twine
            pipenv run twine upload dist/*

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test
      - test_pypi_publish:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - develop
      - pypi_publish:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - main

